# Generated by Django 4.2.5 on 2023-09-07 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_auto_20181115_1953"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0007_auto_20200801_0817"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("website_url", models.CharField(blank=True, max_length=255)),
                ("strip_id", models.CharField(blank=True, max_length=255)),
                ("about_company", models.TextField(blank=True)),
                ("about_you", models.TextField(blank=True)),
                ("logo", models.TextField(blank=True)),
                ("rep_profile", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="State/County"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Zip/Postal Code"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="City"),
                ),
                (
                    "age_range",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Age Range"
                    ),
                ),
                (
                    "income_level",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Income Level"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Seller Profile",
                "verbose_name_plural": "User Seller Profile",
            },
        ),
        migrations.CreateModel(
            name="RepProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("social_media", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Rep Profile",
                "verbose_name_plural": "User Rep Profile",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="State/County"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Zip/Postal Code"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="City"),
                ),
                (
                    "age_range",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Age Range"
                    ),
                ),
                (
                    "income_level",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Income Level"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Education"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("marital_status", models.CharField(blank=True, max_length=255)),
                ("family_type", models.CharField(blank=True, max_length=255)),
                ("occupation", models.CharField(blank=True, max_length=255)),
                ("favourite", models.CharField(blank=True, max_length=255)),
                ("avatar", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=255)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User billing address",
            },
        ),
        migrations.CreateModel(
            name="BillingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("billing_address", models.CharField(blank=True, max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User billing address",
                "verbose_name_plural": "User billing address",
            },
        ),
    ]
